-- AlterTable
ALTER TABLE "DoubleDelegate" ALTER COLUMN "d_name" DROP NOT NULL,
ALTER COLUMN "d_email" DROP NOT NULL,
ALTER COLUMN "d_gender" DROP NOT NULL,
ALTER COLUMN "d_year" DROP NOT NULL,
ALTER COLUMN "d_country" DROP NOT NULL,
ALTER COLUMN "d_phone1" DROP NOT NULL,
ALTER COLUMN "d_phone2" DROP NOT NULL,
ALTER COLUMN "d_course" DROP NOT NULL,
ALTER COLUMN "d_college" DROP NOT NULL,
ALTER COLUMN "d_age" DROP NOT NULL,
ALTER COLUMN "d_prevExp" DROP NOT NULL,
ALTER COLUMN "d_awards" DROP NOT NULL;
